server:
  port: 3000

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/mybatis-plus-handler-demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai'
    username: 'root'
    password: 'root'

mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**/*Mapper.xml

logging:
  level:
    com.qianlingo.mybatisplushandlerdemo: debug